
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_USERPASSWORD}
    url: jdbc:mariadb://${DB_HOST}:3306/team_a

mybatis:
  type-aliases-package: com.green.nottodolist
  mapper-locations: mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html
    tags-sorter: alpha
